#! /usr/bin/perl

use strict;
use warnings;

use Finance::Bank::Cahoot;
use Finance::Bank::Cahoot::CredentialsProvider::Callback;

my $cahoot = Finance::Bank::Cahoot->new(
               credentials => 'ReadLine',
	       credentials_options => { account => '12345678',
					username => 'acmeuser' });
$cahoot->login();

foreach my $account ($cahoot->accounts()) {
  next unless $account->{name} =~ /current/;
  $cahoot->set_account($account->{account});
  my $snapshot = $cahoot->snapshot;
  foreach my $transaction (@$snapshot) {
    print $transaction->date, q{,},
          $transaction->details, q{,},
          $transaction->credit || 0, q{,},
          $transaction->debit || 0, qq{\n};
  }
}
